name: Test Python Tk

on: [push, pull_request]

jobs:
  tests-poetry:
    strategy:
      matrix:
        os: [macos-13]
        python-version: ["3.8.19", "3.8.10", "3.8.17", 3.8.12", "3.9.13", "3.9.19", "3.10.11", "3.10.14", "3.10.12", "3.10.9"]
      fail-fast: false
    name: Py ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        # uses: actions/setup-python@v5
        uses: priyagupta108/setup-python@create_release
        with:
          python-version: ${{ matrix.python-version }}
     
      - name: Run tk script
        if: runner.os != 'Linux'
        run: python tk_min.py
